### ISSUE TITLE
ENH: Meaningful error reporting

### ISSUE THREAD

**Issue by dgarijo** [oeg-upm/morph-kgc#72] opened 2022-07-07 19:06 UTC
#### The problem
Today we spent 30 mins debugging a mapping because we had named the mapping file `.rml` instead of `ttl`. The error prompted us stating that the n3 module could not be loaded. We need better error reporting, especially for silly errors such as this one

#### Describe the Solution you'd Like
Clear errors to address common mistakes. In this case, if an `rml` file is passed, maybe try to parse it in `ttl`?

**Comment by ArenasGuerreroJulian** [comment] 2022-07-08 06:27
Mappings are handled through RDFlib, i.e., error handling on this is delegated to RDFlib. Indeed, it is needed to provide more meaningful error messages in general, this is related to #63

**Comment by ArenasGuerreroJulian** [comment] 2022-10-23 11:53
Mapping files using the `.rml` extensions have been adressed in #80 .

Regarding meaningful error reporting, the issue is similar to #63 . I close this issue and will use #63 as the reference issue for the improvement of error handling.

**Closed by ArenasGuerreroJulian** 2022-10-23 11:53 UTC
Labels: enhancement
